
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  application:
    name: ems
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student?serverTimezone=GMT%2B8
    username: root
    password: root

server:
  port: 80
  servlet:
    context-path: /ems

    jsp:
      init-parameters:
        development: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:xml/*.xml


